### ISSUE TITLE
Script doesn't work with new versions of pybo and botok

### ISSUE THREAD

**Issue by Celso-Scott** [84000/translation-memory-resources#2]
However, I am able to run it by just uninstalling pybo and botok with pip3 commands and installing versions from when we first built the repository:

pybo 0.6.5
botok 0.6.9

It's fine for me to just use the older versions, but this should be updated or noted for anyone emulating this TM workflow. I tried to adjust this myself as I understand basic python portions of the script, but the botok and .yaml portions of the script are a bit beyond me.

**Comment by drupchen** [comment]
solved in fa662977cdf3aa12823f2d800b59872b4ce5359d

**Comment by drupchen** [comment]
oops... just saw that we want to have the words segmented as well.

**Comment by drupchen** [comment]
finally solved in 6b481888c7829c0dfceb190a45c67b46fbabc8b8
